### ISSUE TITLE
overwrite parameter for methods

### ISSUE THREAD

**Issue by mdp0023** [passaH2O/pygeoflood#6]
Might be worth adding an overwrite parameter for methods in pygeoflood workflow. For example, someone who is running script outside of jupyter notebooks inside a plain python script may not want to re-run every function. An overwrite parameter would then allow them to run all methods, creating the appropriate self.vars, without having to wait to recompute all steps.

**Comment by mdp0023** [comment]
Might not actually be necessary: missed the to_paths and from_paths methods, can likely ignore this enhancement

**Comment by markwang0** [comment]
Sounds good, commenting to document our conversation that it would still be useful to be able to save different versions of the outputs, such as different versions of the filtered DEM. Right now we can only save one path for the filtered DEM in a pygeoflood project

**Comment by mdp0023** [comment]
refactored functions to allow custom inputs
